export const Meals = [
  [
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'NoMeal',
      Description: 2,
      AirlineDescription: '',
      Quantity: 0,
      Currency: 'INR',
      Price: 0,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'WHSK',
      Description: 2,
      AirlineDescription: 'Whiskey – 50 ML (2 Miniatures)',
      Quantity: 1,
      Currency: 'INR',
      Price: 1250,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'VGML',
      Description: 2,
      AirlineDescription: 'Veg Meal',
      Quantity: 1,
      Currency: 'INR',
      Price: 400,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'TCSW',
      Description: 2,
      AirlineDescription: 'Tomato Cucumber Cheese Lettuce Sandwich Combo',
      Quantity: 1,
      Currency: 'INR',
      Price: 400,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'CJSW',
      Description: 2,
      AirlineDescription: 'Chicken Tikka Sandwich ombo',
      Quantity: 1,
      Currency: 'INR',
      Price: 500,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'BEER',
      Description: 2,
      AirlineDescription: 'Beer - 330 ML (2 Cans)',
      Quantity: 1,
      Currency: 'INR',
      Price: 1250,
      Origin: 'DAC',
      Destination: 'DEL',
    },
  ],
  [
    {
      AirlineCode: '6E',
      FlightNumber: '2519',
      WayType: 1,
      Code: 'NoMeal',
      Description: 2,
      AirlineDescription: '',
      Quantity: 0,
      Currency: 'INR',
      Price: 0,
      Origin: 'DEL',
      Destination: 'BOM',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '2519',
      WayType: 1,
      Code: 'VGML',
      Description: 2,
      AirlineDescription: 'Veg Meal',
      Quantity: 1,
      Currency: 'INR',
      Price: 400,
      Origin: 'DEL',
      Destination: 'BOM',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '2519',
      WayType: 1,
      Code: 'TCSW',
      Description: 2,
      AirlineDescription: 'Tomato Cucumber Cheese Lettuce Sandwich Combo',
      Quantity: 1,
      Currency: 'INR',
      Price: 400,
      Origin: 'DEL',
      Destination: 'BOM',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '2519',
      WayType: 1,
      Code: 'PTSW',
      Description: 2,
      AirlineDescription: 'Paneer Tikka Sandwich Combo',
      Quantity: 1,
      Currency: 'INR',
      Price: 500,
      Origin: 'DEL',
      Destination: 'BOM',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '2519',
      WayType: 1,
      Code: 'CJSW',
      Description: 2,
      AirlineDescription: 'Chicken Tikka Sandwich ombo',
      Quantity: 1,
      Currency: 'INR',
      Price: 500,
      Origin: 'DEL',
      Destination: 'BOM',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1115',
      WayType: 1,
      Code: 'NoMeal',
      Description: 2,
      AirlineDescription: '',
      Quantity: 0,
      Currency: 'INR',
      Price: 0,
      Origin: 'BOM',
      Destination: 'DAC',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1115',
      WayType: 1,
      Code: 'WHSK',
      Description: 2,
      AirlineDescription: 'Whiskey – 50 ML (2 Miniatures)',
      Quantity: 1,
      Currency: 'INR',
      Price: 1250,
      Origin: 'BOM',
      Destination: 'DAC',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1115',
      WayType: 1,
      Code: 'VGML',
      Description: 2,
      AirlineDescription: 'Veg Meal',
      Quantity: 1,
      Currency: 'INR',
      Price: 400,
      Origin: 'BOM',
      Destination: 'DAC',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1115',
      WayType: 1,
      Code: 'TCSW',
      Description: 2,
      AirlineDescription: 'Tomato Cucumber Cheese Lettuce Sandwich Combo',
      Quantity: 1,
      Currency: 'INR',
      Price: 400,
      Origin: 'BOM',
      Destination: 'DAC',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1115',
      WayType: 1,
      Code: 'PTSW',
      Description: 2,
      AirlineDescription: 'Paneer Tikka Sandwich Combo',
      Quantity: 1,
      Currency: 'INR',
      Price: 500,
      Origin: 'BOM',
      Destination: 'DAC',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1115',
      WayType: 1,
      Code: 'CJSW',
      Description: 2,
      AirlineDescription: 'Chicken Tikka Sandwich ombo',
      Quantity: 1,
      Currency: 'INR',
      Price: 500,
      Origin: 'BOM',
      Destination: 'DAC',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1115',
      WayType: 1,
      Code: 'BEER',
      Description: 2,
      AirlineDescription: 'Beer - 330 ML (2 Cans)',
      Quantity: 1,
      Currency: 'INR',
      Price: 1250,
      Origin: 'BOM',
      Destination: 'DAC',
    },
  ],
];
