export const baggage = [
  [
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'NoBaggage',
      Description: 2,
      Weight: 0,
      Currency: 'INR',
      Price: 0,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPA',
      Description: 2,
      Weight: 5,
      Currency: 'INR',
      Price: 3398,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPB',
      Description: 2,
      Weight: 10,
      Currency: 'INR',
      Price: 6797,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPC',
      Description: 2,
      Weight: 15,
      Currency: 'INR',
      Price: 10195,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPD',
      Description: 2,
      Weight: 30,
      Currency: 'INR',
      Price: 20390,
      Origin: 'DAC',
      Destination: 'DEL',
    },
  ],
  [
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'NoBaggage',
      Description: 2,
      Weight: 0,
      Currency: 'INR',
      Price: 0,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPA',
      Description: 2,
      Weight: 5,
      Currency: 'INR',
      Price: 3398,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPB',
      Description: 2,
      Weight: 10,
      Currency: 'INR',
      Price: 6797,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPC',
      Description: 2,
      Weight: 15,
      Currency: 'INR',
      Price: 10195,
      Origin: 'DAC',
      Destination: 'DEL',
    },
    {
      AirlineCode: '6E',
      FlightNumber: '1104',
      WayType: 2,
      Code: 'XBPD',
      Description: 2,
      Weight: 30,
      Currency: 'INR',
      Price: 20390,
      Origin: 'DAC',
      Destination: 'DEL',
    },
  ],
];
