export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const BOOKING_CONFIRMED = 'BOOKING_CONFIRMED';
export const BOOKING_FAILED = 'BOOKING_FAILED';
export const BOOK_AND_HOLD = 'BOOK_AND_HOLD';

export const PAYMENT_IN_PROGRESS = "PAYMENT_IN_PROGRESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";

export const REFUND_REQUESTED = 'REFUND_REQUESTED';
export const REFUND_IN_PROGRESS = "REFUND_IN_PROGRESS";
export const REFUND_REJECTED = "REFUND_REJECTED";
export const REFUND_QUOTED = "REFUND_QUOTED";
export const REFUND_QUOTE_APPROVED = "REFUND_QUOTE_APPROVED";
export const REFUND_QUOTE_REJECTED = "REFUND_QUOTE_REJECTED";
export const REFUND_QUOTE_EXPIRED = "REFUND_QUOTE_EXPIRED";
export const REFUND_PRELIMINARY_COMPLETED = "REFUND_PRELIMINARY_COMPLETED";
export const REFUND_COMPLETED = "REFUND_COMPLETED";

export const DATE_CHANGE_REQUESTED = 'DATE_CHANGE_REQUESTED';
export const DATE_CHANGE_IN_PROGRESS = 'DATE_CHANGE_IN_PROGRESS';
export const DATE_CHANGE_QUOTED = "DATE_CHANGE_QUOTED";
export const DATE_CHANGE_QUOTE_APPROVED = "DATE_CHANGE_QUOTE_APPROVED";
export const DATE_CHANGE_QUOTE_REJECTED = "DATE_CHANGE_QUOTE_REJECTED";
export const DATE_CHANGE_QUOTE_EXPIRED = "DATE_CHANGE_QUOTE_EXPIRED";
export const DATE_CHANGED = "DATE_CHANGED";
export const DATE_CHANGE_REJECTED = "DATE_CHANGE_REJECTED";

export const NAME_CHANGE_REQUEST = "NAME_CHANGE_REQUEST";
export const NAME_CHANGE_IN_PROGRESS = "NAME_CHANGE_IN_PROGRESS";
export const NAME_CHANGED = "NAME_CHANGED";
export const NAME_CHANGE_REQUEST_REJECTED = "NAME_CHANGE_REQUEST_REJECTED";


export const hotelOptions= [
    { value: '', label: 'All' },
    'BOOKING_REQUEST',
    'BOOKING_CONFIRMED',
    'BOOKING_FAILED',
    'BOOK_AND_HOLD',
    'PAYMENT_IN_PROGRESS',
    'PAYMENT_FAILED',
    'PAYMENT_SUCCESS',
    'REFUND_REQUESTED',
    'REFUND_IN_PROGRESS',
    'REFUND_REJECTED',
    'REFUND_QUOTED',
    'REFUND_QUOTE_APPROVED',
    'REFUND_QUOTE_REJECTED',
    'REFUND_QUOTE_EXPIRED',
    'REFUND_PRELIMINARY_COMPLETED',
    'REFUND_COMPLETED',
    'DATE_CHANGE_REQUESTED',
    'DATE_CHANGE_IN_PROGRESS',
    'DATE_CHANGE_QUOTED',
    'DATE_CHANGE_QUOTE_APPROVED',
    'DATE_CHANGE_QUOTE_REJECTED',
    'DATE_CHANGE_QUOTE_EXPIRED',
    'DATE_CHANGED',
    'DATE_CHANGE_REJECTED',
    'NAME_CHANGE_REQUEST',
    'NAME_CHANGE_IN_PROGRESS',
    'NAME_CHANGED',
    'NAME_CHANGE_REQUEST_REJECTED',
  ].map(item => {
    if (typeof item === 'string') {
      const formatted = item
        .toLowerCase()
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
      return { value: item, label: formatted };
    }
    return item;
  });
  