export const allTransectionData = [
  {
    id: '01',
    type: 'Flight Booking',
    referenceNo: 'TF123456789',
    transectionId: 'TF123456789',
    debit: '5000',
    credit: '5000',
    transactionDate: '04 oct 23 09:40 am',
    status: 'pending',
    requestedBy: 'Md Jwel Rana (admin)',
    amount: '500',
    attachment:
      'https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BG.svg',
  },
  {
    id: '02',
    type: 'Re-Issue',
    referenceNo: 'TF123456789',
    transectionId: 'TF123456789',
    debit: '5000',
    credit: '5000',
    transactionDate: '04 oct 23 09:40 am',
    status: 'pending',
    requestedBy: 'Md Jwel Rana (admin)',
    amount: '500',
    attachment:
      'https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BG.svg',
  },
  {
    id: '03',
    type: 'Void',
    referenceNo: 'TF123456789',
    transectionId: 'TF123456789',
    debit: '5000',
    credit: '5000',
    transactionDate: '04 oct 23 09:40 am',
    status: 'pending',
    requestedBy: 'Md Jwel Rana (admin)',
    amount: '500',
    attachment:
      'https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BG.svg',
  },
  {
    id: '04',
    type: 'Partial Pay',
    referenceNo: 'TF123456789',
    transectionId: 'TF123456789',
    debit: '5000',
    credit: '5000',
    transactionDate: '04 oct 23 09:40 am',
    status: 'pending',
    requestedBy: 'Md Jwel Rana (admin)',
    amount: '500',
    attachment:
      'https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BG.svg',
  },
  {
    id: '05',
    type: 'Partial Due Paid',
    referenceNo: 'TF123456789',
    transectionId: 'TF123456789',
    debit: '5000',
    credit: '5000',
    transactionDate: '04 oct 23 09:40 am',
    status: 'pending',
    requestedBy: 'Md Jwel Rana (admin)',
    amount: '500',
    attachment:
      'https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BG.svg',
  },
  {
    id: '05',
    type: 'Deposti',
    referenceNo: 'TF123456789',
    transectionId: 'TF123456789',
    debit: '5000',
    credit: '5000',
    transactionDate: '04 oct 23 09:40 am',
    status: 'pending',
    requestedBy: 'Md Jwel Rana (admin)',
    amount: '500',
    attachment:
      'https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BG.svg',
  },
];
