export const staffData = [
  {
    id: '01',
    name: 'John Doe',
    phone: '555-1234',
    designation: 'Developer',
    role: 'Admin',
    email: 'john.doe@example.com',
    password: 'securepassword1',
    createdDate: new Date(),
  },
  {
    id: '02',
    name: 'Jane Smith',
    phone: '555-5678',
    designation: 'Designer',
    role: 'User',
    email: 'jane.smith@example.com',
    password: 'securepassword2',
    createdDate: new Date(),
  },
  {
    id: '03',
    name: 'Bob Johnson',
    phone: '555-9876',
    designation: 'Tester',
    role: 'User',
    email: 'bob.johnson@example.com',
    password: 'securepassword3',
    createdDate: new Date(),
  },
  {
    id: '04',
    name: 'Alice Williams',
    phone: '555-4321',
    designation: 'Project Manager',
    role: 'Admin',
    email: 'alice.williams@example.com',
    password: 'securepassword4',
    createdDate: new Date(),
  },
  {
    id: '05',
    name: 'Chris Davis',
    phone: '555-8765',
    designation: 'Analyst',
    role: 'User',
    email: 'chris.davis@example.com',
    password: 'securepassword5',
    createdDate: new Date(),
  },
  {
    id: '06',
    name: 'Eva Brown',
    phone: '555-5678',
    designation: 'Developer',
    role: 'Admin',
    email: 'eva.brown@example.com',
    password: 'securepassword6',
    createdDate: new Date(),
  },
  {
    id: '07',
    name: 'Samuel Miller',
    phone: '555-3456',
    designation: 'Designer',
    role: 'User',
    email: 'samuel.miller@example.com',
    password: 'securepassword7',
    createdDate: new Date(),
  },
  {
    id: '08',
    name: 'Olivia Garcia',
    phone: '555-7890',
    designation: 'Tester',
    role: 'User',
    email: 'olivia.garcia@example.com',
    password: 'securepassword8',
    createdDate: new Date(),
  },
  {
    id: '09',
    name: 'Daniel Clark',
    phone: '555-2345',
    designation: 'Project Manager',
    role: 'Admin',
    email: 'daniel.clark@example.com',
    password: 'securepassword9',
    createdDate: new Date(),
  },
  {
    id: '10',
    name: 'Sophia Taylor',
    phone: '555-6789',
    designation: 'Analyst',
    role: 'User',
    email: 'sophia.taylor@example.com',
    password: 'securepassword10',
    createdDate: new Date(),
  },
];
