export const statusData = [
  { value: 'BOOKING_HOLD', name: 'Hold' },
  { value: 'BOOKING_FAILED', name: 'Failed' },
  { value: 'BOOKING_CANCELLED', name: 'Cancelled' },
  { value: 'BOOKING_PENDING', name: 'Pending' },
  { value: 'ISSUE_REQUEST', name: 'Issue Request' },
  { value: 'ISSUE_IN_PROGRESS', name: 'Issue in Progress' },
  { value: 'ISSUE_REJECTED', name: 'Issue Rejected' },
  { value: 'MANUAL_TICKETED', name: 'Ticketed' },
  { value: 'VOIDED_REQUESTED', name: 'Void Requested' },
  { value: 'TICKET_VOIDED', name: 'Ticked Void' },
  { value: 'REFUND_REQUESTED', name: 'Refund Requested' },
  { value: 'REFUND_IN_PROGRESS', name: 'Refund in Progress' },
  { value: 'REFUND_QUOTED', name: 'Refund Quoted ' },
  { value: 'REFUND_QUOTE_APPROVED', name: 'Refund Quoted Approved' },
  { value: 'REFUND_QUOTE_REJECTED', name: 'Refund Quoted Rejected' },
  { value: 'REFUND_COMPLETED', name: 'Refund Completed' },
  { value: 'REFUND_REJECTED', name: 'Refund Rejected' },
  { value: 'REISSUE_REQUESTED', name: 'Reissue Requested' },
  { value: 'REISSUE_IN_PROGRESS', name: 'Reissue in Progress' },
  { value: 'REISSUE_QUOTED', name: 'Reissue Quoted' },
  { value: 'REISSUE_QUOTE_APPROVED', name: 'Reissue Quoted Approved' },
  { value: 'REISSUE_QUOTE_REJECTED', name: 'Reissue Quoted Rejected' },
  { value: 'REISSUE_COMPLETED', name: 'Reissue Completed' },
  { value: 'REISSUE_REJECTED', name: 'Reissue Rejected' },
  { value: 'TICKET_NO_SHOW', name: 'Ticket no show' },
  { value: 'NO_SHOW_REQUESTED', name: 'No show Reuested' },
  { value: 'NO_SHOW_IN_PROGRESS', name: 'No Show In Progress' },
  { value: 'NO_SHOW_APPROVED', name: 'No Show Approved' },
  { value: 'NO_SHOW_REJECTED', name: 'No Show Rejected' },
  { value: 'BOOKING_EXPIRED', name: 'Booking Expired' },
  { value: 'PARTIAL_REFUND_INITIATED', name: 'Refund Initiated' },
];
